name: modern_auth_ui
description: A modern and clean authentication UI.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  flutter_svg: ^2.0.9
  animated_text_kit: ^4.2.2
  lottie: ^2.7.0
  flutter_animate: ^4.3.0
  shared_preferences: ^2.2.2
  flutter_native_splash: ^2.3.6
  font_awesome_flutter: ^10.6.0
  url_launcher: ^6.2.1
  loading_animation_widget: ^1.2.0+4
  page_transition: ^2.1.0
  glassmorphism: ^3.0.0
  animate_do: ^2.0.0
  http: ^1.2.2
  provider: ^6.0.3
  qr_flutter: ^4.0.0
  logger: ^1.1.0
  flutter_contacts: ^1.1.7+1   
  permission_handler: ^10.2.0 # Nécessaire pour gérer les permissions
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/welcome_image.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/splash.png
  android_12:
    image: assets/images/splash.png
    color: "#FFFFFF"
  web: false

flutter:
  uses-material-design: true

  assets:
    - assets/images/welcome_image.png
    - assets/animations/
    - assets/icones/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
